import {
  contact,
  estate,
  github,
  linkedin,
  naver,
  nia,
  summiz,
  twitter,
} from '../assets/icons';
import {
  ai1,
  ai2,
  ai3,
  amazon1,
  amazon2,
  amazon3,
  chatbot1,
  chatbot2,
  dummy1,
  dummy2,
  ecommerce1,
  ecommerce2,
  jewelry1,
  jewelry2,
  jewelry3,
  jewelry4,
  naver1,
  naver2,
  naver3,
  naver4,
  snapgram1,
  snapgram2,
} from '../assets/images';

export const projects = [
  {
    name: 'Other Projects',
    images: [estate],
    iconsUrl: estate,
    theme: 'btn-back-black',
    linkWebsite: 'https://github.com/salahbm?tab=repositories',
    linkGitHub: 'https://github.com/salahbm?tab=repositories',
    description: [
      'Please visit my GitHub page to see other projects which are not listed above.',
    ],
  },
  {
    name: 'Naver Scraping Web',
    images: [naver1, naver2, naver3, naver4],
    iconsUrl: estate,
    theme: 'btn-back-yellow',
    linkGitHub: 'https://github.com/salahbm/Naver-Scraper',
    linkWebsite: 'https://naver-scraper.vercel.app/',
    description: [
      'Naver Scraping Web is a comprehensive full-stack web application designed for data scraping and visualization using Naver Map and Naver Data API.',
      'This innovative platform automates the process of gathering and analyzing data from desired brands by periodically scraping information from Naver Map and other sources.',
      'Utilizing advanced web scraping techniques, the application extracts and aggregates data such as business details, locations, and customer reviews, providing valuable insights for market research and analysis.',
      'The user-friendly interface allows users to specify their desired brands and parameters for data extraction, empowering them with customizable and actionable data insights.',
      'With seamless integration of Naver Map and Naver Data API, Naver Scraping Web offers a powerful solution for businesses and researchers to access and utilize real-time data effectively.',
    ],
  },
  {
    name: 'Snapgram Social Media Platform',
    images: [snapgram1, snapgram2],
    iconsUrl: estate,
    theme: 'btn-back-black',
    linkGitHub: 'https://github.com/salahbm/snapgram',
    linkWebsite: 'https://example.com/snapgram-social-media',
    description: [
      'Snapgram is a dynamic social media platform inspired by the popular features of Snapchat and Instagram.',
      'Users can enjoy a wide range of functionalities including photo sharing, stories, and messaging, creating an immersive and interactive social experience.',
      'With its sleek design and user-friendly interface, Snapgram offers a seamless way to connect and share moments with friends and followers.',
    ],
  },
  {
    name: 'AI Image Generator and Document Summary',
    images: [ai1, ai2, ai3],
    iconsUrl: estate,
    theme: 'btn-back-red',
    linkGitHub: 'https://github.com/salahbm/ai-web',
    linkWebsite: 'https://ai-web-five-xi.vercel.app/',
    description: [
      "This project harnesses the power of OpenAI's cutting-edge algorithms to generate realistic images and summarize documents automatically.",
      'Using TypeScript and React on the frontend, users can interact with an intuitive interface to generate images and receive concise summaries of lengthy documents.',
      'Cloudinary integration facilitates seamless image storage and manipulation, ensuring optimal performance and scalability.',
      'On the backend, a full-stack MongoDB setup handles data storage and retrieval, providing a robust foundation for managing user-generated content and document summaries.',
      'With a combination of advanced technologies and a user-centric approach, this project aims to streamline content generation and information extraction processes.',
    ],
  },
  {
    name: 'Amazon Price Scraping',
    images: [amazon1, amazon2, amazon3],
    iconsUrl: estate,
    theme: 'btn-back-pink',
    linkGitHub: 'https://github.com/salahbm/amazon-price-scraping',
    linkWebsite: 'https://amazon-price-scraping.vercel.app/',
    description: [
      'Amazon Price Scraping is a powerful tool designed to gather real-time pricing data from Amazon product listings.',
      'Using web scraping techniques, the application extracts product information including prices, ratings, and availability.',
      'The scraped data is then processed and analyzed, providing valuable insights for pricing strategies, market research, and competitive analysis.',
      'This project utilizes cutting-edge technologies to ensure accurate and up-to-date information, empowering users with actionable intelligence to make informed decisions.',
    ],
  },
  {
    name: 'Personal Chatbot',
    images: [chatbot1, chatbot2],
    iconsUrl: estate,
    theme: 'btn-back-yellow',
    linkGitHub: 'https://github.com/salahbm/ChatBot_client',
    linkWebsite: 'https://chatbot-eosin-five.vercel.app/',
    description: [
      'Personal Chatbot is a versatile platform designed to create customizable chatbots tailored to individual needs.',
      'Powered by advanced natural language processing (NLP) algorithms, these intelligent chatbots are capable of understanding and responding to a wide range of customer queries.',
      "Whether it's providing product recommendations, answering FAQs, or assisting with troubleshooting, Personal Chatbot streamlines customer interactions, enhancing user experience and satisfaction.",
      'Built with flexibility and scalability in mind, this project offers a user-friendly interface for designing and deploying chatbots with ease.',
    ],
  },

  {
    name: 'E-commerce [not finished]',
    images: [ecommerce1, ecommerce2],
    iconsUrl: estate,
    theme: 'btn-back-red',
    linkGitHub: 'https://github.com/salahbm/jewelryshop',
    linkWebsite: 'https://jewelryshop-five.vercel.app/',
    description: [
      'A redesign project aimed at improving user experience and enhancing functionality for an existing e-commerce website.',
      'the next js app for jewelry commerse store uses redux, firebase, stripe, tailwind, etc',
    ],
  },
  {
    name: 'MrJoniandCo [under development]',
    images: [jewelry1, jewelry2, jewelry3, jewelry4],
    iconsUrl: estate,
    theme: 'btn-back-pink',
    linkGitHub: 'https://github.com/salahbm/ecommerse-jewelry',
    linkWebsite: 'https://ecommerse-jewelry.vercel.app/',
    description: [
      'MrJoniandCo is an innovative online platform revolutionizing the jewelry shopping experience.',
      'With a focus on personalization and creativity, users can design and customize their own unique jewelry pieces, reflecting their individual style and preferences.',
      'From selecting gemstones and metals to choosing designs and engravings, the platform offers a wide range of customization options to cater to every taste.',
      'With seamless integration of e-commerce functionality, users can easily browse, customize, and purchase their personalized jewelry creations, enjoying a convenient and delightful shopping experience from start to finish.',
      'Experience the joy of self-expression and craftsmanship with MrJoniandCo, where every piece tells a story and celebrates individuality.',
    ],
  },

  {
    name: 'Metapin Extension',
    images: [estate],
    iconsUrl: estate,
    theme: 'btn-back-blue',
    link: 'https://github.com/salahbm/fido2-on-Metamask_extension',
    linkGitHub: 'https://github.com/salahbm/fido2-on-Metamask_extension',
    description: [
      'Metapin Extension is a browser extension that implements FIDO2 passwordless login and signup functionality, inspired by Metamask.',
      'With this extension, users can securely authenticate and access web services without the need for traditional passwords, enhancing security and convenience.',
      'Designed with simplicity and security in mind, Metapin Extension offers a seamless login experience while prioritizing user privacy and data protection.',
    ],
  },
  {
    name: 'Crypto Wallet',
    images: [summiz],
    iconsUrl: estate,
    theme: 'btn-back-black',
    link: 'https://github.com/salahbm/CryptoWallet',
    linkGitHub: 'https://github.com/salahbm/CryptoWallet',
    description: [
      'Crypto Wallet is a versatile mobile wallet application developed using React Native.',
      'It enables users to securely send and receive tokens on the Ethereum main-net and test-nets, providing a convenient solution for managing cryptocurrency assets.',
      'With support for multi-user authentication and token price tracking, Crypto Wallet offers comprehensive functionality for both casual users and experienced traders alike.',
    ],
  },
  {
    name: 'ShopMe',
    images: [estate],
    iconsUrl: estate,
    theme: 'btn-back-pink',
    link: 'https://github.com/salahbm/shopme',
    linkGitHub: 'https://github.com/salahbm/shopme',
    description: [
      'ShopMe is a feature-rich e-commerce website built with Next.js.',
      'Utilizing technologies such as Tailwind CSS, Stripe, Firebase, and Redux Toolkit, ShopMe provides a seamless and enjoyable shopping experience for users.',
      'From product browsing to secure payment processing, ShopMe offers a complete solution for online merchants and shoppers alike.',
    ],
  },
];

export const socialLinks = [
  {
    name: 'Contact',
    iconUrl: contact,
    link: 'https://t.me/imsalah19',
  },
  {
    name: 'GitHub',
    iconUrl: github,
    link: 'https://github.com/salahbm',
  },
  {
    name: 'LinkedIn',
    iconUrl: linkedin,
    link: 'https://www.linkedin.com/in/salahbm/',
  },
];
