/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agata Tomaszewska (https://sketchfab.com/AgataTomaszewska)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plane-flying-circus-game-art-8d6d3260fdf84f3ebbda8f3f3c9b5db2
Title: Plane Flying Circus - Game Art
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import planeScene from '../assets/3d/flyingPlane.glb';
import { useFrame } from "@react-three/fiber";
export function FlyingPlane({ isRotating, ...props }) {
  const ref = useRef();
  const { scene, animations } = useGLTF(planeScene);
  const { actions } = useAnimations(animations, ref);
    useEffect(() => {
      const rotationAction = actions.rotation;
      rotationAction.play().setEffectiveTimeScale(8);
    }, [actions.rotation]);
    
    useFrame(({ clock }) => {
      const initialY = ref.current.position.y;
      const newY = Math.sin(clock.elapsedTime) * 0.002 + initialY;
      ref.current.position.y = newY;
    
      if (isRotating) {
        const initialX = ref.current.position.x;
        const newX = Math.sin(clock.elapsedTime) * 0.002 +initialX;
        ref.current.position.x = newX; // Corrected line: use position.x instead of position.y
      }
    });
    

  return (
    <mesh ref={ref} 
   
{...props}

    >
      // use the primitive element when you want to directly embed a complex 3D
      model or scene
      <primitive object={scene} />
    </mesh>
  
  );
}


