/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agata Tomaszewska (https://sketchfab.com/AgataTomaszewska)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plane-flying-circus-game-art-8d6d3260fdf84f3ebbda8f3f3c9b5db2
Title: Plane Flying Circus - Game Art
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import rocketScene from '../assets/3d/rocket.glb';
import { useFrame } from "@react-three/fiber";
export function Rocket({  ...props }) {
  const ref = useRef();
  const { scene, animations } = useGLTF(rocketScene);
  const { actions } = useAnimations(animations, ref);
  console.log(`file: Rocket.jsx:17 ~ actions:`, actions)
  
    useEffect(() => {
      const flyAction = actions.NaveR;
      flyAction.play()
    }, []);
    
    useFrame(({ clock }) => {
      const initialY = ref.current.position.y;
      const newY = Math.sin(clock.elapsedTime) * 0.002 + initialY;
      ref.current.position.y = newY;
    
 
    });
    

  return (
    <mesh ref={ref} 
{...props}

    >
      // use the primitive element when you want to directly embed a complex 3D
      model or scene
      <primitive object={scene} />
    </mesh>
  
  );
}


