/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agata Tomaszewska (https://sketchfab.com/AgataTomaszewska)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plane-flying-circus-game-art-8d6d3260fdf84f3ebbda8f3f3c9b5db2
Title: Plane Flying Circus - Game Art
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import rocketScene from '../assets/3d/rocket.glb';
import { useFrame } from "@react-three/fiber";

export function Rocket({ ...props }) {
    const ref = useRef();
    const { scene, animations } = useGLTF(rocketScene);
    const { actions } = useAnimations(animations, ref);
  
    const stages = [0.2];
    let currentY = -2;
  
    useEffect(() => {
      const currentStage = stages.findIndex(stage => currentY <= stage);
      if (currentStage !== -1) {
        console.log('Current Stage:', currentStage * 10);
        if (currentY >= stages[stages.length - 1]) {
          const flyAction = actions.NaveR;
          flyAction.reset().play();
          currentY = 0; // Reset to the bottom after playing the animation
        }
      }
    }, [currentY, stages, actions]);
  
    useFrame(() => {
      // Move the rocket steadily up the Y-axis
      currentY += 0.01; // Adjust the speed as needed
  
      // Clamp the Y position to 70% of the screen
      if (currentY > stages[stages.length - 1]) {
        currentY = 0;
      }
  
      ref.current.position.y = currentY;
    });
  
    return (
      <mesh ref={ref} {...props}>
        <primitive object={scene} />
      </mesh>
    );
  }

